### ISSUE TITLE
Tests with multiple examples take significantly longer to run than in previous versions

### ISSUE THREAD

**Issue by jscn** [koterpillar/aloe#112]
I haven't had time to completely characterise this yet, but after upgrading from `v0.0.34` to `v0.1.5`, the time it takes for tests with multiple examples to run has increased significantly. In my particular project which had 192 tests which used to take ~55 minutes to run, following the upgrade the same tests take > 75 minutes to run, at which point the CI runner cancels the build. Aloe also reports each example as a separate test now.

I assume this is something to do with commit 16c37dbbac88f191755aae12e82d58257b5748ed which made it so that each example gets run as a separate function. Presumably there is some significant overhead, either in aloe itself or in my particular project, involved in setting up those functions.

**Comment by koterpillar** [comment]
The change means each _example_ is a _test method_ in Unittest terminology, and therefore has `setUp`/`tearDown` run before/after. If you have hooks that clean up the database, etc. `after_each.example`, you don't need them anymore because you will get a new database for each example. This might help bringing your run time back in line with what it was before.

**Comment by jscn** [comment]
Thanks, we were indeed calling `clear_app` for several apps after each
example. Removing this seems to have about halved the time to run the
tests! However, some tests are relying on object IDs which don't appear to
be getting reset between examples (e.g., we're expecting an object to have
ID 1 but it's actually 56 or something), which seems odd. I would have
expected the ID sequence to be reset if we were getting a new database each
time. I'll keep investigating.

Documenting this kind of change would be really helpful. Might I suggest
adding a changelog to the project?

On Mon, May 16, 2016 at 11:16 AM, Alexey Kotlyarov <notifications@github.com

**Comment by koterpillar** [comment]
I don't think Django will reset sequences between the test runs, you will need to do that manually. However, that shouldn't take as much time as `clear_app`.

Agreed about changelog.

**Comment by jscn** [comment]
Right you are. For anyone else that hits this problem, adding a call to the
`flush` management command in a step decorated with `@before.each_example`
got things working. Not quite a 50% increase in speed with that, but still
pretty close! Thanks Alexey :)

**Comment by koterpillar** [comment]
Closing this, will create a changelog once there are any new changes.

**Comment by koterpillar** [comment]
@jscn how about setting https://docs.djangoproject.com/en/1.9/topics/testing/advanced/#django.test.TransactionTestCase.reset_sequences? Remember that Aloe-generated test cases inherit from the one you specify, see `GHERKIN_TEST_CLASS`.
