### ISSUE TITLE
aloe does not run on win

### ISSUE THREAD

**Issue by wymannmi** [koterpillar/aloe#119]
# Aloe seems not to run on win32/win64 at all.

I would think it appropriate to at least mention this explicitly in the documentation.
## Steps to reproduce.
1. Clean install of python
2. `pip install virtualenv`
3. Create virtual environment
4. Activate virtual environment
5. `pip install aloe`
6. `aloe --help` produces the following stack trace
   
   ```
     (py3) C:\virtual_envs>aloe --help
     Traceback (most recent call last):
       File "c:\progs\python35\Lib\runpy.py", line 170, in _run_module_as_main
         "__main__", mod_spec)
       File "c:\progs\python35\Lib\runpy.py", line 85, in _run_code
         exec(code, run_globals)
       File "C:\virtual_envs\py3\Scripts\aloe.exe\__main__.py", line 9, in <module>
       File "c:\virtual_envs\py3\lib\site-packages\aloe\__init__.py", line 33, in main
         from aloe.runner import Runner
       File "c:\virtual_envs\py3\lib\site-packages\aloe\runner.py", line 17, in <module>
         from aloe.plugin import GherkinPlugin
       File "c:\virtual_envs\py3\lib\site-packages\aloe\plugin.py", line 24, in <module>
         from aloe.result import AloeTestResult
       File "c:\virtual_envs\py3\lib\site-packages\aloe\result.py", line 17, in <module>
         import blessings
       File "c:\virtual_envs\py3\lib\site-packages\blessings\__init__.py", line 5, in <module>
         import curses
       File "c:\progs\python35\Lib\curses\__init__.py", line 13, in <module>
         from _curses import *
     ImportError: No module named '_curses'
   ```

All other interactions I have tried so far--in particular running a feature file--produce the same result.
## System information

Operating System: Windows 10, Version 1511, Build 10586.545

```
> python
Python 3.5.1 (v3.5.1:37a07cee5969, Dec  6 2015, 01:54:25) [MSC v.1900 64 bit (AMD64)] on win32

> pip list 
aloe (0.1.8)
blessings (1.6)
future (0.15.2)
gherkin-official (4.0.0)
nose (1.3.7)
pip (8.1.2)
repoze.lru (0.6)
setuptools (26.1.1)
wheel (0.29.0)
```
## Dependency on `curses` via `blessings`

It seems to be well-known that `curses` is not supported on Windows builds of Python. `blessings` depends on `curses`. In the `blessings` project there is an open issue regarding this with long discussion. However the issue is quite old (2012) and seems not to move in any definitive direction.

[Issue 21: completly fails on win32/64](https://github.com/erikrose/blessings/issues/21)
## Suggestion/Questions
- Would it be possible to make the dependency on `blessings` optional? 
- Would it be possible to offer an option to use an alternative (e.g. colorama)

**Comment by koterpillar** [comment]
Thank you for the issue report. I will investigate making the `blessings` dependency optional, but can't guarantee any serious Windows support. If there is a CI system that tests on Windows, a patch adding support for it will help.

**Comment by brarcher** [comment]
> If there is a CI system that tests on Windows, a patch adding support for it will help.

Just as a note, [AppVeyor](https://www.appveyor.com/) can be used as a CI for Windows. Here is an example of using AppVeyor for Python:

https://github.com/ogrisel/python-appveyor-demo/blob/master/appveyor.yml

AppVeyor provides free usage of their system for open source projects. The [Check](https://github.com/libcheck/check/blob/master/appveyor.yml) project is also taking advantage of this.

FYI.

**Comment by koterpillar** [comment]
I have enabled AppVeyor on a branch in #133, but there are issues with character encodings (among other) - if you have a Windows environment, you're welcome to take a look.

**Comment by brarcher** [comment]
I do not have a Windows environment, but taking a look at the encoding issue and searching online I see the [following suggestion](https://stackoverflow.com/questions/5419/python-unicode-and-the-windows-console):
```
pip install win-unicode-console
```
This should allow python to transparently write to the console in such a way that it is recognized.

If that does not work out, there is a way to configure the AppVeyor test run to stay up for an hour, giving you remote access to it to poke around. This will allow you to debug on Windows for up to an hour at a time. I've done this to debug various issues in the past. [Here](https://www.appveyor.com/docs/how-to/rdp-to-build-worker/) is information on how to set that up.

Hope it helps.
