### ISSUE TITLE
placing step files

### ISSUE THREAD

**Issue by ramast** [koterpillar/aloe#120]
With Lettuce, step files where placed in `features/steps/*.py`.
Trying to run your lettuce test cases with aleo will give you that error:

`StepDiscoveryError("Cannot load step definition file: /path/to/features/steps/my_step.py")`
with no further information (python2).

To find the real error I needed to go to
`aloe/fs.py` and replace

```
                try:
                    cls.importer.importFromPath(filename, module_name)
                except ImportError as exc:
                    raise_from(
                        StepDiscoveryError(
                            "Cannot load step definition file: '%s'" % filename
                        ),
                        exc
                    )
```

with

`cls.importer.importFromPath(filename, module_name)`

The error was can't import `features`, a module that I haven't tried to import in my step code.
Turns out that unlike lettuce, features directory must contain `__init__.py` for the steps to load.

I would like to:
1. Add notice in http://aloe.readthedocs.io/projects/aloe-django/en/latest/porting.html about this issue.
2. Update "Step Loading" section here http://aloe.readthedocs.io/en/latest/steps.html to include an example like features.html page.
3. I'd suggestion removing the try/except while importing the file so that developer can find out why the module failed to load

**Comment by koterpillar** [comment]
Agree on points 1 and 2, will try to make documentation more clear. In current Python versions, the exception that caused the `StepDiscoveryError` would be displayed alongside it, so both the step module that failed to load and the actual exception are available to the developer.

**Comment by ramast** [comment]
Steps to reproduce:
1. remove `features/__init__.py` from any test case you have.
2. run harvest.

You will get Error in file `app/features/steps/my_step.py` , can't import features.
this file would in fact have no errors what so ever.

Also in case the file has an actual error, I am not sure if the full stack trace would be mentioned?

**Comment by koterpillar** [comment]
You should get this:

```
(traceback of ImportError)

The above exception was the direct cause of the following exception:

(traceback of StepDiscoveryError)
StepDiscoveryError("Cannot load step definition file: /path/to/features/steps/my_step.py")
```

Are you still trying on old Python?

**Comment by ramast** [comment]
Yes, I am trying with `python2.7`.
I get error similar to that except that it state the reason "can't import features".
In all cases the error is cryptic and doesn't explain why you couldn't import the step. (is it a syntax error? which line? is it a missing `__init__.py` ? is it some other problem?

**Comment by koterpillar** [comment]
Both errors will be displayed on Python 3. In case of a syntax error, it will be displayed as the "direct cause". I'll see if I can detect this and offer more help in an error message.
