### ISSUE TITLE
absorb was removed

### ISSUE THREAD

**Issue by devicodev** [koterpillar/aloe#128]
Hi Guys,
 
Could you please point me out how can I store object or methods in world like it was before in lettuce ? Our test suite was designed with using this feature in mind. We are going to migrate to aloe but aloe has a pretty good limitations comparison to lettuce that requires as more efforts that we expected. May be you can provide some clear idea are you planning to use absorb annotation in the nearest future ?

**Comment by koterpillar** [comment]
You can assign to attributes of the world directly:

```python
from aloe import before, world

@before.all
def absorb_things():
    world.thing = my_thing()
```

Because Aloe tests are based on `unittest.TestCase`, you can also provide your own base test class and add necessary attributes in its `setUp`.
