### ISSUE TITLE
Handling quotes in Gherkin features

### ISSUE THREAD

**Issue by skqr** [koterpillar/aloe#131]
For some reason we're having problems with quotes and punctuation in the Gherkin text.

We've had to remove quotes (as in "we've" for "weve") and any punctuation (commas and colons) in order for Aloe to run properly.

The examples on https://aloe.readthedocs.io/en/latest/ show no punctuation, which worries me a little. Can Aloe really not read Gherkin files with punctuation or single quotes in them?

**Comment by koterpillar** [comment]
Can you share an example of a failing feature, and the error message or unexpected result you're getting?

This is an example of a feature that uses quotes: https://github.com/aloetesting/aloe/blob/master/tests/callbacks_app/features/testcase_methods.feature (and see more features in that directory). It is part of Aloe's testsuite, so the automated tests verify it is working.

**Comment by koterpillar** [comment]
Additionally, [aloe-django](https://github.com/aloetesting/aloe_django) uses quotes extensively for the Django model-related steps, and that is also verified by automated tests.
