### ISSUE TITLE
Support coloured output on Windows

### ISSUE THREAD

**Issue by AndyDeany** [koterpillar/aloe#136]
Many other testing tools have coloured output on Windows. Aloe should have it too.

**Comment by AndyDeany** [comment]
From reading other issues I understand that you use `blessings` which relies on `curses`, which isn't available on Windows. I suppose this would mean that you'd need to convert the colouring from using `blessings` to something else.

If someone points me in the right direction - an alternative way of colouring output, and the files I'd need to change (I think `aloe/result.py`, but there may be others?), I'd be willing to have a shot at making a pull request for this.

**Comment by koterpillar** [comment]
Thanks for offering to help! The color support for Windows will be most welcome.

From Aloe side, you need to look at the [Terminal](https://github.com/aloetesting/aloe/blob/master/aloe/result.py#L73) class and its testing counterparts. This encapsulates all the coloring logic with calls like `term.tag`, `term.passed` and so on.

I don't know much about the Windows side though. I think there are some Windows counterparts for the ANSI escape sequences, as well as some opt-in support for ANSI escape sequences in WSL.

**Comment by koterpillar** [comment]
Fixed via #139.
