### ISSUE TITLE
Why isnt there a "each_scenario" ?

### ISSUE THREAD

**Issue by kingbuzzman** [koterpillar/aloe#145]
Why isnt there a "each_scenario" ? There is a "each_feature", "each_example", ... why is this one missing?

**Comment by koterpillar** [comment]
`each_example` will run before/after each _scenario_ once if the scenario has no examples, you most likely want this one. Or do you have a case where you need to distinguish between scenarios with and without examples?

**Comment by kingbuzzman** [comment]
@koterpillar Oh it does? Should have looked into this a little more before posting. ~Is this documented anywhere?~ nm https://github.com/aloetesting/aloe#migrating-from-lettuce . I think this will do just fine.

Thanks.
