### ISSUE TITLE
Non-ascii characters in README.md can cause install errors

### ISSUE THREAD

**Issue by Ben-RK** [koterpillar/aloe#147]
The `ã` character in a contributor's name can cause ascii decoding errors when trying to pip install aloe. The problem is found on the following line of the README.md:
`Copyright (C) <2010-2012> Gabriel Falcão <gabriel@nacaolivre.org>`

The error produced is:
```
     Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-wj0k1i6w/aloe/setup.py", line 19, in <module>
        long_description=readme.read(),
      File "/home/utils/Python-3.6.1/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 2494: ordinal not in range(128)
```

**Comment by koterpillar** [comment]
Which version of Python and pip are you using?

**Comment by nikolas** [comment]
This can be solved by explicitly encoding the file with utf-8 when opening it. See: https://github.com/aloetesting/aloe/pull/152
