### ISSUE TITLE
continue rest features when there is a scenario failure 

### ISSUE THREAD

**Issue by godsarmy** [koterpillar/aloe#153]
What do you think such use case?

1 define a scenario to cover a code feature.
2 code has bug so the scenario keeps failing.
3 we fix code bug and scenario becomes success.

In step2, if i run the scenario, then i receives a failure in result. But i do not care as i know there is a bug.
I found if a scenario fails, the rest features in the same feature directory are not launched.
Is it possible to continue to run the rest of features in this case?

Sorry i did not find an option in the aloe cli

**Comment by koterpillar** [comment]
Can you please show an example output of Aloe and how are you running it? The default behavior is to run all scenarios in all features, even if some fail. However, if a step in a scenario fails, no further steps in that scenario will run.

**Comment by godsarmy** [comment]
you are write. I think i occasionally added `--stop` param. My fault :(
