### ISSUE TITLE
Extract and Use Scenario Name

### ISSUE THREAD

**Issue by APhillips-CSInc** [koterpillar/aloe#158]
I am trying to use the value in the Scenario field in my steps. I've tried looking through parser.py for Scenario.name but it does not seem as though the name method has been implemented (even though it's in the [documentation](https://aloe.readthedocs.io/en/latest/classes.html#scenario)?). Perhaps I'm calling for it incorrectly. 

`world.scen_name = parser.Scenario.name()`

**Comment by koterpillar** [comment]
You can use the scenario name through the step object:

https://aloe.readthedocs.io/en/latest/steps.html

> The first parameter passed into the decorated function is the Step object built for this step.

`Step` [has a `scenario` property](https://aloe.readthedocs.io/en/latest/classes.html#aloe.parser.Step.scenario), and `Scenario` [has a `name` property](https://aloe.readthedocs.io/en/latest/classes.html#aloe.parser.Scenario.name).

So for your use case:

```
@step("I use the scenario name")
def mystep(self):
    world.scen_name = self.scenario.name
```

In your example, you are calling `name` as a _method_ on the `Scenario` _class_, not on a concrete object. I suggest familiarising yourself with the difference between properties and methods, and classes and objects.
