### ISSUE TITLE
Sometimes top frame in traceback is `wrapped()`

### ISSUE THREAD

**Issue by danni** [koterpillar/aloe#34]
Sometimes my tracebacks look like this:

```
Traceback (most recent call last):
  File "/app/python_env/local/lib/python2.7/site-packages/aloe/registry.py", line 178, in wrapped
    return function(*args, **kwargs)
  File "ixlogin/features/profile_management/change_email.feature", line 18, in Change email
    When I log in with username "alice_l" and password "secret"
```

**Comment by koterpillar** [comment]
Is it always a particular feature? Does it vary from run to run?

**Comment by koterpillar** [comment]
This just happened to me while running the tests of Aloe Webdriver. It disappeared on a subsequent run with no changes at all.

**Comment by koterpillar** [comment]
This is intended(?) behavior of `unittest`. When the exception is caught, only the frames down from it are printed. This includes aloe (unfortunately) but doesn't include `unittest` itself.

I'm not sure this is a bug; if anything, _removing_ the top frame (with `wrapped`) would be a feature.
