### ISSUE TITLE
Define public (Python) API

### ISSUE THREAD

**Issue by koterpillar** [koterpillar/aloe#45]
Need to define a list of modules that can be safely imported from Aloe for implementing things like Aloe-Django.

Currently there's an API for writing applications that use Aloe (`before`, `after`, `step`, `world`) and testing (`aloe.testing`). Modules like `aloe.runner` and `aloe.testclass` are pretty random and existing imports can be easily broken by refactoring.

**Comment by danni** [comment]
I think it's what is in the docs.

**Comment by koterpillar** [comment]
You're right, what I actually want to do is different, this makes no sense.
