### ISSUE TITLE
New Cucumber parser raises CompositeParserException for strings containing "/"

### ISSUE THREAD

**Issue by jscn** [koterpillar/aloe#48]
I have some tests for visiting URLs with multiple examples in a table:

```
        When I visit site page "<url>"

        Then I should not see "<page_name>"
        And the browser's URL should contain "next=/<url>"
        And I should see an element with id of "login_frame"

        Examples:
            | page_name           | url                                    |
            | My Projects         | my/projects                            |
```

When I run these tests with aloe v0.0.24 all is well, but running the same tests with aloe v0.0.25 causes the following error:

```
  File "/home/josh/work/qipps/python_env/local/lib/python2.7/site-packages/gherkin3/parser.py", line 83, in parse
    raise CompositeParserException(context.errors)
CompositeParserException: Parser errors:
(8:0): unexpected end of file, expected: #TableRow, #DocStringSeparator, #StepLine, #TagLine, #ExamplesLine, #Comment, #Empty
```

I'm not sure at this stage whether the error only occurs with such values in tables.

**Comment by koterpillar** [comment]
Is that the start of the file?

**Comment by koterpillar** [comment]
This looks suspiciously like the last item of https://github.com/koterpillar/aloe#migrating-from-lettuce.

**Comment by jscn** [comment]
The feature file appears to me to be well formed. E.g., the file starts with "Feature: xyz", has a "Background" block, and the scenario starts with "Scenario Outline:".

**Comment by koterpillar** [comment]
Can you post the whole feature?

**Comment by jscn** [comment]
Sure thing, it's here: https://gist.github.com/jscn/5cbe16c41c81def7f183

**Comment by koterpillar** [comment]
Can't reproduce. See `test-feature-parse-error-48` branch and https://travis-ci.org/koterpillar/aloe/builds/79783743 - it parses just fine. (PEP8 errors on long lines so the build fails.)

Just in case, can you check that `gherkin3` is at `3.1.1` or later?

**Comment by jscn** [comment]
```
$ pip freeze | grep gherk
gherkin3==3.1.1
```

Still occurring for me with the project in question, but your test passes okay.

**Comment by koterpillar** [comment]
Is the error perhaps inside a `behave_as`?

Failing that, perhaps scrub the project directory clean of _everything_ except the feature file but so it still fails, archive and upload somewhere so I can have a look?

**Comment by koterpillar** [comment]
Please reopen if you still get this.
