### ISSUE TITLE
Features files location

### ISSUE THREAD

**Issue by michelts** [koterpillar/aloe#53]
Hi @koterpillar,

The docs gives this example for features loading:

```
one/
__init__.py
features/
    one.feature
    two/
    three.feature
    four.feature
examples/
    five.feature
two/
features/
    six.feature
```

I am not sure but I think there is a mess in the identation to indicate subfolders. I think **init**.py and features dir was supposed to be inside one directory, am I right?

I think you mean:

```
one/
    __init__.py
    features/
        one.feature
        two/
            three.feature
            four.feature
examples/
    five.feature
two/
    features/
        six.feature
```

Anyway, I achieve a directory structure a bit different:

```
one/
    sample1/
        sample1.feature
        steps.py
        __init__.py
    sample2/
        sample2.feature
        steps.py
        __init__.py
    __init__.py
```

The docs don't put clear if the rules are inclusive or exclusive:
- Are named `features`;
- Are located in a directory containing packages, that is, all their parent  directories have an `__init__.py` file.

I'm starting with aloe yesterday, porting from lettuce, I'm not able to answer this question myself yet :)

**Comment by koterpillar** [comment]
I've updated the documentation in #57, is it clear now?

**Comment by michelts** [comment]
It is much more clear, but I insist that I could use a structure different from the documented:

```
one/
    sample1/
        sample1.feature
        steps.py
        __init__.py
    sample2/
        sample2.feature
        steps.py
        __init__.py
    __init__.py
```

If I run aloe inside the _one_ directory, all features will run, no matter the lack of a _features_ directory.

You tell:

>  If features are not specified on the command line, Aloe will look for features in directories that are both:
> - Named `features`;
> - Located in a directory containing packages

But I think you mean:

>  If features are not specified on the command line, Aloe will look for features files that are both:
> - Named `*.features`;
> - Located in a directory containing packages

Or something like this :)

The features directory isn't necessary.

**Comment by michelts** [comment]
Sorry, it is my fault. I tested again the environment I proposed and it doesn't work at all.

Aloe found my features files (running with --collect-only proved that) but don't reach the steps files as I proposed, I need any folder called _feature_, just as you stated.

I'm still a bit confused about how steps and features are found, I end up in the following:

```
features/
    sample1/
        sample1.feature
        steps.py
        __init__.py
    sample2/
        sample2.feature
        steps.py
        __init__.py
    __init__.py
```

And I called aloe as the following:

```
$ aloe -w features -a my_tag
```

I'm ok with that.

**Comment by koterpillar** [comment]
Are you saying that a feature _not_ in "features" directory is run? It's not supposed to, and I have added a test to #57 to show it.

**Comment by michelts** [comment]
No. Features not in "features" directory is not **run**, but because **steps** aren't found. The **features** actually are found. Suppose the following structure:

```
my_tests/
    sample1/
        sample1.feature
        steps.py
        __init__.py
```

... when I run aloe:

```
$ cd my_tests
$ aloe
E
======================================================================
ERROR: Test 2.1 (exemplo2.exemplo: Add numbers)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/michel/Projetos/aloe/my_tests/exemplo2/exemplo.feature", line 35, in Test 2.4
    | 35     | 85     |
  File "/home/michel/.virtualenvs/aloe/src/myaloe/aloe/registry.py", line 163, in wrapped
    return function(*args, **kwargs)
  File "/home/michel/Projetos/aloe/my_tests/exemplo2/exemplo.feature", line 24, in Test 2.4
    Given I fill 50 in calculator
  File "/home/michel/.virtualenvs/aloe/src/myaloe/aloe/registry.py", line 163, in wrapped
    return function(*args, **kwargs)
  File "/home/michel/.virtualenvs/aloe/src/myaloe/aloe/exceptions.py", line 58, in undefined_step
    raise NoDefinitionFound(step)
NoDefinitionFound: The step r"Given I fill 50 in calculator" is not defined

----------------------------------------------------------------------
Ran 1 test in 0.001s
```

I think going further will be too much thorough. I and any other caught with this doubt should follow the docs ;)

**Comment by koterpillar** [comment]
No, you actually found a bug. `exemplo.feature` (or `sample1.feature`?) should not have been collected. This is now fixed in #57, please check.

**Comment by michelts** [comment]
Still wake up? :smile: 

It is working as expected now.

**Comment by koterpillar** [comment]
Merged and released.
