### ISSUE TITLE
Make step.hashes and step.table as list instead of tuple.

### ISSUE THREAD

**Issue by michelts** [koterpillar/aloe#54]
I'm from lettuce and I use to compare browser data with step data passed through hashes. I use the following approach:

``` python
rows = world.browser.find_by_css('table tbody tr')
for row in rows:
    data = step.hashes.pop(0)
    cells = row.find_by_css('td')
    assert_equals(cells[0], data['Name'])
assert_true(len(step.hashes.data), 0, 'You must spend all hashes data!')
```

I avoid using zip to join both lists because if one of then is shorter than expected, it would truncate the other.

Aloe make the step.hashes a tuple instead of a list. That makes me write one extra line to convert the hashes to a list.

This is not a big problem, but I'm wondering if you see any impediment to turn the hashes a list instead of tuple at aloe side.

What do you think?

**Comment by koterpillar** [comment]
``` python
data = step.hashes.pop(0)
```

This is precisely the reason not to do it. Imagine what happens when a step is a part of a scenario outline, and you "spend" all your hashes on the first example.

**Comment by michelts** [comment]
I try it :)

Suppose the following features file:

```
Feature: Add numbers

    Scenario Outline: Add numbers
        Given I fill 50 in calculator
        Given I fill <Number> in calculator
        When I press sum
        Then should be <Result> at result
        And I should spend
            | Name |
            | A    |
            | B    |

    Examples:
        | Number | Result |
        | 35     | 85     |
        | 70     | 120    |
```

And suppose the following step file (I included only the pertinent step):

``` python
@step(r'I should spend')
def spend(step):
    assert_equals(step.hashes, [{'Name': 'A'}, {'Name': 'B'}])
    assert_equals(step.table, [('Name',), ('A',), ('B',)])
    assert_equals(step.keys, ['Name'])

    for i in range(2):
        step.hashes.pop(0)

    for i in range(3):
        step.table.pop()

    step.keys.pop()

    assert_equals(step.hashes, [])
    assert_equals(step.table, [])
    assert_equals(step.keys, [])
```

When I run it, both outlines passes.

It seems that an outline is copied in the aloe.parser.py:Step.resolve_substitutions, before being actually used. The copies would share the _table_\* list, but the [resolve_substitutions method redefines the **table** to resolve variables](https://github.com/koterpillar/aloe/blob/master/aloe/parser.py#L363).

To make this test work, I converted any tuple() to list() in the referred file.

Do you still think we must avoid this approach? If you approve, I can apply the fixes and write a test.

Let me know if you agree ;)

**Comment by koterpillar** [comment]
I still think the step properties should be immutable. A step hook or something else can rely on the original value of `table` and such, and be surprised that they are no longer there.

In fact, the pretty printer (`-v 3`) accesses steps, scenarios, etc. to print them, including after they ran. I didn't try that, but I suspect if you "spend" your table it will not be properly printed afterwards.

**Comment by michelts** [comment]
It seems to be printed normally just because the table is copied before scenario being run. But I'm convinced, this approach can be achieved by any interested through hooks (I can copy hashes to a mutable attribute before each step).

I must admit when I first try it in lettuce, I expected the step hashes to be immutable.

Thanks!
