### ISSUE TITLE
Instructions to an alternative to the lettuce's debug option

### ISSUE THREAD

**Issue by michelts** [koterpillar/aloe#70]
Hi @koterpillar 

Lettuce has a cool option to run the server in debug mode. This is specially useful if you run scenarios in selenium/splinter with chrome/firefox and want to see traceback in the screen. I use to run harvest like:

```
$ ./manage.py harvest features -t wip --pdb -d
```

This way, I would stop when reach an error and the traceback would be in the screen.

Aloe can't offer an alternative: it is a django matter. Maybe we could rely in the override_settings decorator but I don't think it's worth, I achieve an easier approach: I can see the same traceback defining a logger.

I won't see the traceback in the screen but I would see in the output console before pdb stops it.

This is not a problem of aloe, but it would be great to have a tips section in the docs with instructions like that.

Would you accept a pull request with this?

**Comment by koterpillar** [comment]
I see several things here:
1. `DEBUG = True`. This can be set in a base test class's `setUpClass` or similar, the same as for Python tests. Yes, this warrants a note in the documentation dealing with migrating from Lettuce.
2. Breaking into debugger. Nose has a [Debug plugin](http://nose.readthedocs.org/en/latest/plugins/debug.html), perhaps it does what you want already?
3. Seeing the traceback in console. I'm not sure what happens currently for live server exceptions in Python tests, but if they are not printed, consider installing a handler on `got_request_exception`.

**Comment by michelts** [comment]
Cool!

I forgot about the GHERKIN_TEST_CLASS configuration option of aloe_django. Defining debug there solves the problem, I will describe that in the docs and make a pull request.

Breaking into debugger wasn't a problem and the traceback in the console isn't necessary anymore, once we can set debug before run the tests. Anyway, if someone don't want to subclass aloe_django.TestCase, [the second example of django logger documentation](https://docs.djangoproject.com/en/dev/topics/logging/#examples) does the trick, it makes the traceback to be printed in console.

I'm welcome with the solution achieved here, but if you prefer, I can go deeper than just point it in the docs, I can write an option for the harvest command in aloe_django, maybe a flag like --django-debug... What do you think about it?

**Comment by koterpillar** [comment]
Aloe should not contain options that are not specific for Gherkin tests, and `django-debug` will be one of them. If you want, add it to django-nose or Django instead.

**Comment by michelts** [comment]
Ok thanks!

**Comment by koterpillar** [comment]
Added to https://aloe.readthedocs.org/projects/aloe-django/en/latest/porting.html.
