### ISSUE TITLE
Passing arguments to behave_as

### ISSUE THREAD

**Issue by zuBux** [koterpillar/aloe#92]
Hi,

Maybe this is not an issue but I wasn't able to find anything relevant in the documentation.

I have the following step:

```
@step
def user_login(self, user):
    '''user (\w+) is logged in'''
```

I want  to create a new step whose sentence will be "user (\w+) logs in" which will behave in the exact same way as user_login. The only reason for doing this is to stay as close to natural language as possible (e.g In many Given statements passive voice is better, while in When statements active voice seems more correct).

I created the following new step:

```
@step
def user_login_2(self, user):
    ''' user (\w+) logs in'''
    self.behave_as("Given user (\w+) is logged in")
```

If I use a hardcoded value in behave_as (e.g `self.behave_as("Given user testuser1 is logged in")`) the new step runs fine. However if I use the (\w+) regex, I get the following error : 

> NoDefinitionFound: The step r"Given user (\w+) is logged in" is not defined

Is there a way of passing the value to behave_as?

**Comment by koterpillar** [comment]
Just pass the parameter as you would to any other Python function.

``` python
self.behave_as("Given user {} is logged in".format(user))
```

**Comment by zuBux** [comment]
I should have thought of that, thanks!I guess you can close the issue.
